#!/usr/bin/env python3

import colors as c
 

print(c.red +'''
welcome to magic eight ball!
enter your qesstin below
'''+c.reset)
answer=[
    'yes.',
    'no.',
    'maybe.',
    'shut up',
    'mortal kombat',
    'avgn whach him',
    'sing a song',
    'fat butt',
    'huge me',
    'markipeler',
    'lugenut',
    'stop it',
    'ok goodbye',
    'im dead',
    'have fun',
    'stupid head',
    'im dumb',
    'im done',
    'fnaf',
    'bye',
]


   else:
       answer = random.choice(answers)
       print(c.random_color()+ (answer + c.reset) 
